#!/bin/sh

docker-compose down

mkcert -cert-file ./docker/ssl/frontend.local.pem -key-file ./docker/ssl/frontend.local.key frontend.local

docker-compose up -d --build --force-recreate

docker exec -i -u root qw-frontend-node bash -c 'cat > /etc/pki/ca-trust/source/anchors/qw.api.pem' < $(mkcert -CAROOT)/rootCA.pem
docker exec -i -uroot qw-frontend-node bash -c 'update-ca-trust extract'

docker exec -i qw-frontend-node npm i
docker exec -i qw-frontend-node npm i -d
docker exec -i qw-frontend-node npm run build