version: '3.7'

networks:
  qw_frontend_internal-communications:
    name: qw_frontend_internal-communications
    ipam:
      config:
        - subnet: 159.85.0.0/16
  qw_backend_entry-point:
    external: true

services:
  qw_frontend_web-server:
    container_name: qw-frontend-nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      qw_frontend_internal-communications:
        ipv4_address: 159.85.173.80
      qw_backend_entry-point:
    depends_on:
      - qw_frontend-runtime_env
    volumes:
      - ./docker/virtual-host.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/ssl/certs
      - .:/var/www

  qw_frontend-runtime_env:
    container_name: qw-frontend-node
    image: blackmaizegod/php-fpm:8.2
    restart: unless-stopped
    networks:
      - qw_frontend_internal-communications
    volumes:
      - .:/var/www